---
name: Land-blocking Test

on:
  push:
    branches:
      - auto
      - canary

jobs:
  build-and-run-cluster-test:
    name: Build images and run cluster test
    steps:
      - name: setup_aws_ecr_login
        run: |
          exit 1